name: Custom Actions
on: 
  push:
    branches: 7_custom_actions
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      
      - name: Load & Cache dependencies
        uses: ./.github/actions/cached-deps

      - name: Lint project
        run: npm run lint

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      
      - name: Load & Cache dependencies
        uses: ./.github/actions/cached-deps
        id: cache
        with:
          caching: false
          message: 'Hello from the workflow user!'

      - name: Test project
        id: test
        run: npm test
      
      - name: Upload reports
        if: ${{ failure() && steps.test.outcome == 'failure' }}
        uses: actions/upload-artifact@v3
        with:
          name: test-report
          path: test-report.json
      
      - name: Print C.A. output
        run: echo '${{ steps.cache.outputs.something }}'

  build:
    needs: [lint, test]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      
      - name: Load & Cache dependencies
        uses: ./.github/actions/cached-deps

      - name: Build project
        id: test
        run: npm run build
      
      - name: Upload build
        uses: actions/upload-artifact@v3
        with:
          name: project-build
          path: dist

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download build
        uses: actions/download-artifact@v3
        with:
          name: project-build
          path: dist

      - name: Deploy project
        run: |
          ls
          echo "Deploying..."