name: Event Filters & Activity Types
on:
  push:
    branches: 2_events
  
  pull_request:
    types: opened
    branches: 2_events
  
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Output event data
        run: echo "${{toJson(github.event)}}"
      
      - name: Get code
        uses: actions/checkout@v3
      
      - name: Install locked dependencies
        run: npm ci
      
      - name: Test project
        run: npm test

      - name: Lint project
        run: npm run lint

      - name: Build project
        run: npm run build

      - name: Deploy project
        run: npm run build