name: Environment Variables and Secrets
on: push
env:
  SECRET_MESSAGE: "This is a secret message."
jobs:
  test:
    environment: Example
    env:
      REPO_ENV_SECRET: ${{ secrets.REPO_ENV_SECRET }}
      REPO_ENV_VARIABLE: ${{ vars.REPO_ENV_VARIABLE }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: node-deps-${{ hashFiles('package-lock.json') }}
      
      - name: Install dependencies
        run: npm ci
      
      - name: Lint
        run: npm run lint

      - name: Test
        run: npm run test
      
      - name: Echo Repository Environment Variable
        run: echo "${{ env.REPO_ENV_VARIABLE }}"

      - name: Echo Repository Environment Secret
        run: echo "${{ env.REPO_ENV_SECRET }}"
  
  build:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: node-deps-${{ hashFiles('**/package-lock.json') }}
      
      - name: Install dependencies
        run: npm ci
      
      - name: Build project
        run: npm run build

      - name: Upload build
        uses: actions/upload-artifact@v3
        with:
          name: app-build
          path: dist
      
      - name: Print Workflow Secret
        run: echo $SECRET_MESSAGE
  
  deploy:
    needs: build
    runs-on: ubuntu-latest
    env:
      SECRET_MESSAGE: "Overwritten secret at Job level."
      SECRET_FROM_GITHUB: ${{ secrets.MY_GITHUB_SECRET }}
    steps:
      - name: Download build
        uses: actions/download-artifact@v3
        with:
          name: app-build

      - name: Echo Job Env
        run: |
          echo "${{ env.SECRET_MESSAGE }}"
          echo $SECRET_MESSAGE
      
      - name: Echo Step Env
        env:
          SECRET_MESSAGE: "Overwritten secret at Step level."
        run: |
          echo "${{ env.SECRET_MESSAGE }}"
          echo $SECRET_MESSAGE
      
      - name: Echo Secret
        run: echo ${{ env.SECRET_FROM_GITHUB }}
      
      - name: Deploy
        run: |
          ls
          echo "Deploying..."