name: Matrix Strategies Demo
on: push
jobs:
  build:
    continue-on-error: true
    strategy:
      matrix:
        node-version: [16, 18, 20]
        operating-system: [ubuntu-latest, windows-latest]
        include:
          - node-version: 17
            operating-system: ubuntu-latest
        exclude:
          - node-version: 18
            operating-system: windows-latest

    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v3
      
      - name: NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 
      
      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build