name: Second Workflow
on: workflow_dispatch
jobs:
  example-job:
    runs-on: ubuntu-latest
    steps:
      - name: Multiline Step
        run: |
          echo "Line 1"
          echo "Line 2"
          echo "Line 3"